### ISSUE TITLE
how about the memory has used in running?

### ISSUE THREAD

**Issue by wlz987** [oufuzhao/CLIB-FIQA#1]
gpu memory: 10+G
memory:?

这模型占用这么大吗,

**Comment by oufuzhao** [comment]
hello，我是用4090跑的。我刚刚测了下，占的内存是9709MiB /  24564MiB，所以可能是刚好超了你gpu的内存。

**Comment by oufuzhao** [comment]
Hi, I have modified the inference.py to reduce the GPU memory via torch.no_grad(). The inference results do not change, but it can significantly reduce the memory requirements of the GPU. After modification, the GPU memory needed for the inference is 2389MiB.
