### ISSUE TITLE
How to crop the face in custom data？

### ISSUE THREAD

**Issue by HeathHose** [oufuzhao/CLIB-FIQA#3]
Hello,

Thank you for sharing such an excellent project! Can you share the code on how to crop faces so that I can test it in custom data?

Thank you!

**Comment by oufuzhao** [comment]
Hi @HeathHose,

Thanks for your interest in our work. One of the simple ways is to install facenet-pytorch and then import MTCNN to crop. Specifically, you can refer to [here](https://github.com/timesler/facenet-pytorch).
